// This file is generated by Slice Machine. Update with care!

import Bleikros from './Bleikros';
import Gulros from './Gulros';
import Hvitros from './Hvitros';
import Raudros from './Raudros';

export {
	Bleikros,
	Gulros,
	Hvitros,
	Raudros,
};

export const components = {
	bleikros: Bleikros,
	gulros: Gulros,
	hvitros: Hvitros,
	raudros: Raudros,
};
