// This file is generated by Slice Machine. Update with care!

import Flower from './Flower';
import Gulros from './Gulros';
import Gulrot from './Gulrot';
import Ros from './Ros';

export {
	Flower,
	Gulros,
	Gulrot,
	Ros,
};

export const components = {
	flower: Flower,
	gulros: Gulros,
	gulrot: Gulrot,
	ros: Ros,
};
