// This file is generated by Slice Machine. Update with care!

import Flower from './Flower';
import TimeImageRight from './TimeImageRight';

export {
	Flower,
	TimeImageRight,
};

export const components = {
	flower: Flower,
	time_image_right: TimeImageRight,
};
